### ISSUE TITLE
Line number and hunk_id in `hunk_labels.json`

### ISSUE THREAD

**Issue by emadpres** [sherbold/replication-kit-2020-line-validation#1]
Hi

I'm trying to understand the [`hunk_labels.json`](https://github.com/sherbold/replication-kit-2020-line-validation/blob/main/data/hunk_labels.json) file, but can not figure out how **line numbers** work. They seem to be relative to a certain hunk with the given `hunk_id`. But then I can not understand how such IDs are computed. So I have the following two questions:
1. How are `hunk_id`s obtained?
2. How can I convert the line numbers in your data to file-level line numbers?

Thanks in advance

**Comment by sherbold** [comment]
The `hunk_id` entries are the object ids of the hunks in the SmartSHARK database. If you want to access line numbers, you need to fetch the hunks from our MongoDB, which contains all this information (https://smartshark.github.io/dbreleases/). 

You can then also work directly against the MongoDB, the hunk_labels.json is only a small exerpt to make the replication kit self-contained. The fifth code cell in the replication notebook shows how the validation data is retrieved from the MongoDB.

**Comment by emadpres** [comment]
Thanks, @sherbold. I've started downloading the full mongo database. 
Another question concerning `hunk` collection in the database. Consider the following entry:
```json
{
    "file_action_id": {
        "$oid": "5c78e563fc263631761d0882"
    },
    "new_start": 36,
    "new_lines": 14,
    "old_start": 30,
    "old_lines": 0,
    "content": "...",
    "lines_manual": {
        "aaghamohammadi": {
            "test": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
        }
    }
}
```
For getting the file-level line numbers, should I use `old_start` or `new_start`? I mean, the actual line numbers, in this example, are `[36, 37, ..., 36+13]` or `[30, 31, ..., 30+13]`?

**Comment by sherbold** [comment]
The old lines is the location of hunk within the file prior to the commit, the new lines are the lines after the changes are applied. In you case, this means the hunk started in line 36 before the commit, and starts in line 30 after the commit. This is possible because there may be multiple changes (hunks) applied to the same file within a commit. Within our DB, all changes to a file within a commit are grouped by the file_action.

**Comment by emadpres** [comment]
Thanks for your clarification. I totally understand the concept of `new_start` and `old_start`. I also quickly looked at `file_action` which seems to be a summary of changes that happened to each file.

However, I still don't understand how I can interpret the `manual_line` values (i.e., what does `[0,1,2,..]` refer to?)

**Comment by sherbold** [comment]
Those are the lines in the content of the hunk.

**Comment by emadpres** [comment]
I'm not sure if I understand what you refer to as the "content of the hunk"? 

Let me clarify the problem by an example. Consider the following entry from the `hunk` collection:
```json
{
	"_id":{"$oid":"5bef24e383ad2f56e61ca868"},
	"file_action_id":{"$oid":"5bef24e383ad2f56e61ca862"},
	"new_start":237,
	"new_lines":10,
	"old_start":220,
	"old_lines":15,
	"content":"...",
	"lines_manual":{
		"aaghamohammadi":{
			"documentation":[0,1,3,5,6,7,11,12,20,21],
			"whitespace":[2,13],
			"test":[8,9,14,16,17,18,19]
		}
	}
}
```

Here is the preview of [the hunk it refers to](https://github.com/apache/commons-rdf/commit/7046ea1e38a0da9b1c8ef8716ac7667fd96f7de7#diff-4d968cdb039fd5ba7e1cf081ee4b81210c6a1b659a9b12a6a4faff996927b416). I labeled the line numbers in three ways: <ins>yellow</ins>, <ins>red</ins>, <ins>green</ins>

<img width="686" alt="hunk-1" src="https://user-images.githubusercontent.com/2047884/152178061-d67d3b57-7899-4b38-b065-7eb3f0a4029a.png">

As we can see, lines 0,2,16 (yellow) are white spaces. But the labeling information (`lines_manual`) tells us `[2,13]` are whitespace. Neither "red", "green", or "yellow" numbering matches this information. Can you clarify this a bit, please?


<details>
<summary> How did I find the hunk?</summary>

Starting from the hunk object I put above, I fetched relevant objects from other collections (see below) and ended up at: https://github.com/apache/commons-rdf/commit/7046ea1e38a0da9b1c8ef8716ac7667fd96f7de7#diff-4d968cdb039fd5ba7e1cf081ee4b81210c6a1b659a9b12a6a4faff996927b416


`file_action`
```json
{
	"_id":{"$oid":"5bef24e383ad2f56e61ca862"},
	"file_id":{"$oid":"5bef24e283ad2f56cc1ca84f"},
	"commit_id":{"$oid":"5bef24e383ad2f56e61ca85e"},
	"mode":"M","size_at_commit":18856,"lines_added":79,"lines_deleted":45,
	"is_binary":false,
	"parent_revision_hash":"25cc1f1839c9d99adbaf92ab740d482eaf0f4606"
}
```
#### `file`
```json
{
	"_id":{"$oid":"5bef24e283ad2f56cc1ca84f"},
	"vcs_system_id":{"$oid":"5bef24dc35e3ea2b7bc08208"},
	"path":"api/src/test/java/org/apache/commons/rdf/api/AbstractRDFTest.java"
}
```
#### `vcs`
```json
{
	"_id":{"$oid":"5bef24dc35e3ea2b7bc08208"},
	"url":"https://github.com/apache/commons-rdf.git",
	"project_id":{"$oid":"5beebd870da3ef21a62b756e"},
	"last_updated":{"$date":"2018-11-16T21:13:16.874Z"},
	"repository_type":"git",
	"repository_file":{"$oid":"5dcbf72e2ecf182bf5d3ab89"}
}
```
#### `commit`
```json
{
	"_id":{"$oid":"5bef24e383ad2f56e61ca85e"},
	"vcs_system_id":{"$oid":"5bef24dc35e3ea2b7bc08208"},
	"revision_hash":"7046ea1e38a0da9b1c8ef8716ac7667fd96f7de7",
	"parents":["25cc1f1839c9d99adbaf92ab740d482eaf0f4606"],
	"linked_issue_ids":[{"$oid":"5bf4332fed024056f5b30577"}],
	"labels":{"documentation_javadoc":true,"adjustedszz_bugfix":true,"documentation_technicaldept_remove":false,"documentation_technicaldept_add":false,"refactoring_keyword":false,"documentation_javainline":true,"issueonly_bugfix":true,"testchange_javacode":true,"refactoring_codebased":true,"issueonly_featureadd":true,"validated_bugfix":true,"issuefasttext_bugfix":true},
	"author_date_offset":0,
	"committer_date_offset":0,
	"author_id":{"$oid":"58c1133102ca40f8bfb1e2a9"},
	"message":"COMMONSRDF-51: Don't assume langtag case is preserved\n\nalso test .equals() both ways\n",
	"branches":["refs/remotes/origin/master","refs/remotes/origin/HEAD","refs/remotes/origin/fluent-parser","refs/remotes/origin/fluent-parser-impl","refs/heads/master"],
	"committer_id":{"$oid":"58c1133102ca40f8bfb1e2a9"},
	"author_date":{"$date":"2017-01-23T11:20:30.000Z"},
	"committer_date":{"$date":"2017-01-23T11:20:30.000Z"},
	"fixed_issue_ids":[{"$oid":"5bf4332fed024056f5b30577"}],
	"validations":["issue_links"],"szz_issue_ids":[{"$oid":"5bf4332fed024056f5b30577"}]
}
```
</details>

**Comment by sherbold** [comment]
You must use the `content` field of the hunk. There can be different textual diffs, as there are different algorithms for diffs. Sometimes, the diff algorithm we used is not the same as the algorithm used by Github.

**Comment by emadpres** [comment]
As you suggested I looked at the `content` and it matches the GitHub preview I posted above. Here is the `content` value:
```diff
-                
-        // However these should all be true
+
+        // However these should all be true using .equals
         assertEquals(lower, lower);
-        assertEquals(lower, upper);
-        assertEquals(lower, mixed);
-        assertEquals(upper, lower);
+        assertEqualsBothWays(lower, upper);
+        assertEqualsBothWays(lower, mixed);
         assertEquals(upper, upper);
-        assertEquals(upper, mixed);
-        assertEquals(mixed, lower);
-        assertEquals(mixed, upper);
+        assertEqualsBothWays(upper, mixed);
         assertEquals(mixed, mixed);
-
-        // And then by java.lang.Object contract, also the hashcode:
-        assertEquals(lower.hashCode(), upper.hashCode());
-        assertEquals(lower.hashCode(), mixed.hashCode());        
+        // Note that assertEqualsBothWays also checks
+        // that .hashCode() matches
```

So to wrap up the discussion, I just want to understand how did assign line numbers for lines you inspected for filling the `lines_manual` field in the `hunk` collection? (yellow numbering, red numbering, or green numbering that I showed in my previous post?)

**Comment by sherbold** [comment]
For the commit you are using, you would get the following (label, line number, line in content):

```
d 06 -        assertEquals(lower, mixed);
d 07 -        assertEquals(upper, lower);
t 08 +        assertEqualsBothWays(lower, upper);
t 09 +        assertEqualsBothWays(lower, mixed);
  10          assertEquals(upper, upper);
d 11 -        assertEquals(upper, mixed);
d 12 -        assertEquals(mixed, lower);
w 13 -        assertEquals(mixed, upper);
t 14 +        assertEqualsBothWays(upper, mixed);
  15          assertEquals(mixed, mixed);
t 16 -
t 17 -        // And then by java.lang.Object contract, also the hashcode:
t 18 -        assertEquals(lower.hashCode(), upper.hashCode());
t 19 -        assertEquals(lower.hashCode(), mixed.hashCode());        
d 20 +        // Note that assertEqualsBothWays also checks
d 21 +        // that .hashCode() matches
```

(the labels for this hunk are obviously bad)

Please note that you should *not* use the lines manual directly, unless you want to investigate how individual raters labeled a commit. Instead, you should use the field lines_verified, which is requires that we have four raters and at least three of them agree with each other. See, e.g., this hunk: 

```
{ 
    "_id" : ObjectId("5a82f5aa912063217a8893d3"), 
    "file_action_id" : ObjectId("58c898f3c03bb4351dbcb4c2"), 
    "new_start" : NumberInt(291), 
    "new_lines" : NumberInt(1), 
    "old_start" : NumberInt(291), 
    "old_lines" : NumberInt(1), 
    "content" : "-    public Collection getDependencies(String rootModuleConf, String[] confs) {\n+    public Collection getDependencies(String rootModuleConf, String[] confs, String requestedConf) {\n", 
    "lines_manual" : {
        "aaghamohammadi" : {
            "bugfix" : [
                NumberInt(0), 
                NumberInt(1)
            ]
        }, 
        "KKC" : {
            "bugfix" : [
                NumberInt(0), 
                NumberInt(1)
            ]
        }, 
        "davisjam" : {
            "bugfix" : [
                NumberInt(0), 
                NumberInt(1)
            ]
        }, 
        "dvmarcilio" : {
            "bugfix" : [
                NumberInt(0), 
                NumberInt(1)
            ]
        }
    }, 
    "lines_verified" : {
        "bugfix" : [
            NumberInt(0), 
            NumberInt(1)
        ]
    }
}
```

**Comment by emadpres** [comment]
Your annotated example clarified everything. Thanks a lot. Also thanks for pointing out the `lines_verified` field.

To wrap up for future readers, the `lines_manual` follow the **yellow** numbering patterns I showed above. Thus, I need to consider all `content`, `new_start`, and `old_start` fields to map `lines_manual` values to their real line numbers.
